name: q_agency_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  dio: ^4.0.4
  retrofit: ^3.0.1+1
  json_annotation: ^4.4.0
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  connectivity_plus: ^2.2.1

dev_dependencies:
  json_serializable: ^6.1.5
  retrofit_generator: ^3.0.0
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter
  test: ^1.19.5
  analyzer: ^2.8.0
  test_api: ^0.4.8

flutter: 
  uses-material-design: true

